swagger: "2.0"
info:
  title: Full Flow Api
  description: API description in Markdown.
  version: 1.0.0

host: localhost
schemes:
  - http
  - https

paths:
  /users:
    get:
      operationId: getAllUsers
      summary: Get all users
      description: Returns a list of all users.
      produces:
        - application/json
      responses:
        200:
          description: A list of users
          schema:
            type: array
            items:
              $ref: "model.json#/definitions/User"

  /users/{userId}/tasks:
    get:
      operationId: getUserTasks
      summary: Get tasks for a specific user
      description: Returns a list of tasks assigned to a specific user.
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
      produces:
        - application/json
      responses:
        200:
          description: A list of tasks
          schema:
            type: array
            items:
              $ref: "model.json#/definitions/Task"

  /tasks:
    post:
      operationId: createTask
      summary: Create a new task
      description: Creates a new task and assigns it to a user.
      consumes:
        - application/json
      parameters:
        - in: body
          name: create_task_request
          required: true
          schema:
            $ref: "model.json#/definitions/CreateTaskRequest"
      produces:
        - application/json
      responses:
        201:
          description: Task created successfully
          schema:
            $ref: "model.json#/definitions/Task"

  /tasks/{taskId}:
    get:
      operationId: getTaskById
      summary: Get a task by ID
      description: Returns a task by its ID.
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      produces:
        - application/json
      responses:
        200:
          description: A task object
          schema:
            $ref: "model.json#/definitions/Task"
    put:
      operationId: updateTask
      summary: Update a task
      description: Updates an existing task.
      consumes:
        - application/json
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
        - in: body
          name: task
          required: true
          schema:
            $ref: "model.json#/definitions/Task"
      produces:
        - application/json
      responses:
        200:
          description: Task updated successfully
          schema:
            $ref: "model.json#/definitions/Task"

    delete:
      operationId: deleteTask
      summary: Delete a task
      description: Deletes a task by its ID.
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      responses:
        204:
          description: Task deleted successfully
